### ISSUE TITLE
Help with Vonk.Facade.Relational, R4, .Net 8.0 Parameter Detection Not Working

### ISSUE THREAD

**Issue by charlejc** [FirelyTeam/Vonk.Facade.Relational#6]
### Discussed in https://github.com/FirelyTeam/firely-net-sdk/discussions/2745

<div type='discussions-op-text'>

<sup>Originally posted by **charlejc** March 26, 2024</sup>
I'm trying to update to .Net 8.0 and Vonk.Facade.Relation 4.7.1 and other Vonk 4.7.1 packages. I've implemented the QueryFactory patern and inherited code like the example below.

My problem is that the parameter detection does not seem to be working and the only override function that is being called is the one:

`
	public class ObservationQueryFactory : RelationalQueryFactory<myObservation, myRelationalQuery<myObservation>>, IResourceSpecificQueryFactory
	{
		public override myRelationalQuery<myObservation> AddValueFilter(string parameterName, TokenValue value)
		{
// This code is not being called....
			if(String.Compare(parameterName, VonkConstants.ParameterNames.Id, StringComparison.OrdinalIgnoreCase) == 0
				|| String.Compare(parameterName, "identifier", StringComparison.OrdinalIgnoreCase) == 0)
			{
				return PredicateQuery(observation => observation.Id == value.Code);
			}
                        ....
                }

		public override myRelationalQuery<myObservation> AddValueFilter(string parameterName, RawValue value)
		{
// This code is called instead :-( ....
			throw new NotImplementedException();
		}
         }
`

An error is being swallowed that complains that:

System.Security.Cryptography.XmlSerializers, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL cannot be found. 

I'm not sure if that is the cause of the problem. I'm assuming the webhost is trying to read the specification.zip file that is present in the output directory and process monitor shows it being read, but not many parameters are found when reading the xsd files present in the zip.

Any help or pointers would be greatly appreciated.

Thanks!</div>

**Comment by alexzautke** [comment]
Hi @charlejc, happy to help here. Could you indicate if you are currently have a Firely Server license or if you are trying out Firely Server as part of a trial version?


In Version 4.7.1, .NET 8 is not supported. Firely Server v4.x only runs on .NET 6. We are currently migrating to .NET 8. This explains the underlying exception that you are seeing. Could you run it on .NET 6 and see if you are having the same issues?

Thanks!

**Comment by charlejc** [comment]
I do have a Firely Server license. 

Same problem with .net 6.0

Here's where the issue is deriving from:

![image](https://github.com/FirelyTeam/Vonk.Facade.Relational/assets/5399735/2a524908-7ce7-4733-aaaa-f6e7a576617f)

What I haven't figured out yet is how the IEnumerable<VonkSearchParameter> enumerable is populated. Something is not configured correctly and it isn't obvious to me, yet, what needs to be done to fix it.

I also got two new swallowed errors with .net 6.0:

![image](https://github.com/FirelyTeam/Vonk.Facade.Relational/assets/5399735/e5dc7e6a-bf92-4ff8-aeec-95f3a605b1da)

and

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly '...\bin\Debug\net6.0\System.Security.Cryptography.Algorithms.XmlSerializers.dll'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by alexzautke** [comment]
@charlejc Thank you, do you have access to the support desk via our JIRA system? Or support can then figure step by step out what's going wrong here. If you don't have access to Firely Server ticket system, would you mind sending an email to server@fire.ly?

Could you also share any startup logs from Firely Server and a copy of your appsettings?

**Comment by charlejc** [comment]
I sent an email requesting access to the support desk.

Attached is the appsettings and a copy of the console output that was generated during web host start up.


I've replaced any sensitive text with an ellipsis ( ... )
[appsettings.json](https://github.com/FirelyTeam/Vonk.Facade.Relational/files/14775918/appsettings.json)
[console output.txt](https://github.com/FirelyTeam/Vonk.Facade.Relational/files/14775919/console.output.txt)

**Comment by charlejc** [comment]
I got access to the support desk. Do you recommend that I recreate the support request there and close this issue?

**Comment by alexzautke** [comment]
Yes, please!
